def main ():
    print ("Solve A Murder: Choose Your Own Adventure")
    print ("")
    print ("Eric is found dead in his dorm room, there is a bottle of pills lying next to him. The police have already")
    print ("determined that it was a homicide and are beginning to start an investigation. The police have narrowed the")
    print ("search down to four suspects;Sam, Eric's roommate; Owen, Eric's basketball coach; Katie, Eric's girlfriend;")
    print ("and Margo, Eric's ex-girlfriend. Can you help the police solve the case and catch the killer?")
    print ("")
    print ("Hello Detective! Are you excited to find out who the killer is? At the end of this story you will get two")
    print ("guesses to figure out who the killer is. Let's get started!")
    print ("")
    print ("First we will start out with basic information.")
    print ("")
    print ("1. The Coroner's Report")
    print ("2. Eric's Personal File")
    print ("")
    files = input("Enter the number of the file you want to view first:")
    if files == 1:
        print ("")
        print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones, the")
        print ("pills inside the container were actually cyanide. Eric tested positive for the growth hormone and")
        print ("cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
        print ("")
        print ("Now that you have looked over the Coroner's Report, let's take a look at Eric's Personal File.")
        print ("")
        print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
        print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing his")
        print ("homework and practicing basketball. There are mixed emotions around the campus about Eric's death,")
        print ("some are devastated and others aren't affected at all.")
    else:
        print ("")
        print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
        print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing his")
        print ("homework and practicing basketball. There are mixed emotions around the campus about Eric's death,")
        print ("some are devastated and others aren't affected at all.")
        print ("")
        print ("Now that you have looked over the Eric's Personal File, let's take a look at the Coroner's Report.")
        print ("")
        print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones, the")
        print ("pills inside the container were actually cyanide. Eric tested positive for the growth hormone and")
        print ("cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
    print ("")
    print ("Let's Get Started with the interviews who would you like to start with?")
    print ("")
    print ("1. Sam")
    print ("2. Owen")
    print ("3. Katie")
    print ("4. Margo")
    print ("")
    interview = input("Pick the number of the person you want to interview first:")
    if interview == 1:
        print ("")
        print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles. He")
        print ("explains that when he isn't studying, he is reading one of his favorite books, M is for Murder. Sam is")
        print ("in the top of his chemistry class and likes to work in the lab for extra credit, which is where he was")
        print ("at the time of the murder. Sam thinks that Owen is the killer since Owen is always pushing Eric to be a")
        print ("better player and stop messing around.")
        print ("")
        print ("Now that you have spoken to Sam, let's see what the others have to say. Pick the next person to")
        print ("interview.")
        print ("")
        print ("1. Owen")
        print ("2. Katie")
        print ("3. Margo")
        print ("")
        interview1 = input("Pick the number of the person you want to interview next:")
        if interview1 == 1:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that you have spoken to Owen, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Katie")
            print ("2. Margo")
            print ("")
            interview11 = input("Pick the number of the person you want to interview next:")
            if interview11 == 1:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
        elif interview1 == 2:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that you have spoken to Katie, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Owen")
            print ("2. Margo")
            print ("")
            interview12 = input("Pick the number of the person you want to interview next:")
            if interview12 == 1:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
        else:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time of")
            print ("Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric all")
            print ("for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that you have spoken to Margo, let's see what the others have to say. Pick the next person to")
            print ("interview")
            print ("")
            print ("1. Owen")
            print ("2. Katie")
            print ("")
            interview13 = input("Pick the number of the person you want to interview next:")
            if interview13 == 1:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
            else:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
    elif interview == 2:
        print ("")
        print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
        print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back, but")
        print ("claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at the")
        print ("supply store getting more balls for the big game. Owen thinks that Katie is the killer because she")
        print ("is always with him and was mad because he was giving all his time to basketball.")
        print ("")
        print ("Now that you have spoken to Owen, let's see what the others have to say. Pick the next person to")
        print ("interview.")
        print ("")
        print ("1. Sam")
        print ("2. Katie")
        print ("3. Margo")
        print ("")
        interview2 = input("Pick the number of the person you want to interview next:")
        if interview2 == 1:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that you have spoken to Sam, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Katie")
            print ("2. Margo")
            print ("")
            interview21 = input("Pick the number of the person you want to interview next:")
            if interview21 == 1:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
        elif interview2 == 2:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that you have spoken to Katie, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Margo")
            print ("")
            interview22 = input("Pick the number of the person you want to interview next:")
            if interview22 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
        else:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time of")
            print ("Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric all")
            print ("for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that you have spoken to Margo, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Katie")
            print ("")
            interview23 = input("Pick the number of the person you want to interview next:")
            if interview23 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
            else:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
    elif interview == 3:
        print ("")
        print ("Katie is really upset and starts crying during the interview saying that she doesn't know what she will")
        print ("do now that Eric is gone. She says that she loved Eric and would never do anything to hurt him. During")
        print ("her free time she likes to go to parties and hang out with Eric, Katie was at cheerleading practice at")
        print ("time of Eric's murder. Katie says that Margo is the killer because she was jealous of Katie and Eric's")
        print ("relationship, and Margo couldn't stand it.")
        print ("")
        print ("Now that you have spoken to Katie, let's see what the others have to say. Pick the next person to")
        print ("interview.")
        print ("")
        print ("1. Sam")
        print ("2. Owen")
        print ("3. Margo")
        print ("")
        interview3 = input("Pick the number of the person you want to interview next:")
        if interview3 == 1:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that you have spoken to Sam, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Owen")
            print ("2. Margo")
            print ("")
            interview31 = input("Pick the number of the person you want to interview next:")
            if interview31 == 1:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
        elif interview3 == 2:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that you have spoken to Owen, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Margo")
            print ("")
            interview32 = input("Pick the number of the person you want to interview next:")
            if interview32 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Margo. Margo was shocked that anyone wanted to kill Eric, she said he was")
                print ("always a kind, gentleman around her. She was upset because Eric was saying that he wanted to")
                print ("get back together with her but kept going back to Katie. Margo also loves reading and writing,")
                print ("she was at the library at the time of Eric's murder working on her book. Margo says that Katie")
                print ("is the killer because she wanted Eric all for herself and if she couldn't have him no one")
                print ("could.")
            else:
                print ("")
                print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman")
                print ("around her. She was upset because Eric was saying that he wanted to get back together with her")
                print ("but kept going back to Katie. Margo also loves reading and writing, she was at the library at")
                print ("the time of Eric's murder working on her book. Margo says that Katie is the killer because she")
                print ("wanted Eric all for herself and if she couldn't have him no one could.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
        else:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that you have spoken to Margo, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Owen")
            print ("")
            interview33 = input("Pick the number of the person you want to interview next:")
            if interview33 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
            else:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
    else:
        print ("")
        print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
        print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
        print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
        print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
        print ("all for herself and if she couldn't have him no one could.")
        print ("")
        print ("Now that you have spoken to Margo, let's see what the others have to say. Pick the next person to")
        print ("interview.")
        print ("")
        print ("1. Sam")
        print ("2. Owen")
        print ("3. Katie")
        print ("")
        interview4 = input("Pick the number of the person you want to interview next:")
        if interview4 == 1:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that you have spoken to Sam, let's see what the others have to say. Pick the next person to")
            print ("interview")
            print ("")
            print ("1. Owen")
            print ("2. Katie")
            print ("")
            interview41 = input("Pick the number of the person you want to interview next:")
            if interview41 == 1:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
            else:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
        elif interview4 == 2:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that you have spoken to Owen, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Katie")
            print ("")
            interview42 = input("Pick the number of the person you want to interview next:")
            if interview42 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Katie. Katie is really upset and starts crying during the interview saying")
                print ("that she doesn't know what she will do now that Eric is gone. She says that she loved Eric and")
                print ("would never do anything to hurt him. During her free time she likes to go to parties and hang")
                print ("out with Eric, Katie was at a cheerleading practice at time of Eric's murder. Katie says that")
                print ("Margo is the killer because she was jealous of Katie and Eric's relationship, and Margo")
                print ("couldn't stand it.")
            else:
                print ("")
                print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
                print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
                print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at")
                print ("a cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because")
                print ("she was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
        else:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that you have spoken to Katie, let's see what the others have to say. Pick the next person to")
            print ("interview.")
            print ("")
            print ("1. Sam")
            print ("2. Owen")
            print ("")
            interview43 = input("Pick the number of the person you want to interview next;1.Sam or 2.Owen:")
            if interview43 == 1:
                print ("")
                print ("Sam says that he didn't really know Eric that well since they weren't in the same social")
                print ("circles. He explains that when he isn't studying, he is reading one of his favorite books, M is")
                print ("for Murder. Sam is in the top of his chemistry class and likes to work in the lab for extra")
                print ("credit, which is where he was at the time of the murder. Sam thinks that Owen is the killer")
                print ("since Owen is always pushing Eric to be a better player and stop messing around.")
                print ("")
                print ("Now you will talk to Owen. Owen explains that he pushes Eric because he sees that Eric has the")
                print ("potential to be a better player if he puts in the time and effort. Owen has previously been")
                print ("arrested for assault ten years back, but claims he isn't like that anymore. Owen devotes most")
                print ("of his time to basketball, so he was at the supply store getting more balls for the big game.")
                print ("Owen thinks that Katie is the killer because she is always with him and was mad because he was")
                print ("giving all his time to basketball.")
            else:
                print ("")
                print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better")
                print ("player if he puts in the time and effort. Owen has previously been arrested for assault ten")
                print ("years back, but claims he isn't like that anymore. Owen devotes most of his time to basketball,")
                print ("so he was at the supply store getting more balls for the big game. Owen thinks that Katie is")
                print ("the killer because she is always with him and was mad because he was giving all his time to")
                print ("basketball.")
                print ("")
                print ("Now you will talk to Sam. Sam says that he didn't really know Eric that well since they weren't")
                print ("in the same social circles. He explains that when he isn't studying, he is reading one of his")
                print ("favorite books, M is for Murder. Sam is in the top of his chemistry class and likes to work in")
                print ("the lab for extra credit, which is where he was at the time of the murder. Sam thinks that Owen")
                print ("is the killer since Owen is always pushing Eric to be a better player and stop messing around.")
    print ("")
    print ("Now that you have interviewed all the suspects here is some other evidence that might be useful in your")
    print ("investigation. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills on her")
    print ("phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
    print ("")
    print ("Now let's go back and review the evidence. Would you like to revisit anything. Keep in mind that you only")
    print ("get to revisit up to two things.")
    print ("")
    print ("1. Coroner's Report")
    print ("2. Eric's Personal File")
    print ("3. Sam's Interview")
    print ("4. Owen's Interview")
    print ("5. Katie's Interview")
    print ("6. Margo's Interview")
    print ("7. The Case Evidence")
    print ("8. I don't need to review anything")
    print ("")
    review = input("Please enter the number of what you would like to do next:")
    if review == 1:
        print ("")
        print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones, the")
        print ("pills inside the container were actually cyanide. Eric tested positive for the growth hormone and")
        print ("cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review1 = input("Please enter the number of what you would like to do next:")
        if review1 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review1 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 2:
        print ("")
        print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
        print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing his")
        print ("homework and practicing basketball. There are mixed emotions around the campus about Eric's death, some")
        print ("are devastated and others aren't affected at all.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review2 = input("Please enter the number of what you would like to do next:")
        if review2 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review2 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 3:
        print ("")
        print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles. He")
        print ("explains that when he isn't studying, he is reading one of his favorite books, M is for Murder. Sam is")
        print ("in the top of his chemistry class and likes to work in the lab for extra credit, which is where he was")
        print ("at the time of the murder. Sam thinks that Owen is the killer since Owen is always pushing Eric to")
        print ("be a better player and stop messing around.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review3 = input("Please enter the number of what you would like to do next:")
        if review3 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review3 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 4:
        print ("")
        print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
        print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
        print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
        print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
        print ("she is always with him and was mad because he was giving all his time to basketball.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review4 = input("Please enter the number of what you would like to do next:")
        if review4 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review4 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 5:
        print ("")
        print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
        print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
        print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
        print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
        print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review5 = input("Please enter the number of what you would like to do next:")
        if review5 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review5 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 6:
        print ("")
        print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
        print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
        print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
        print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
        print ("all for herself and if she couldn't have him no one could.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review6 = input("Please enter the number of what you would like to do next:")
        if review6 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review6 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    elif review == 7:
        print ("")
        print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills on")
        print ("her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
        print ("")
        print ("Would you like to look at anything else detective?")
        print ("")
        print ("1. Coroner's Report")
        print ("2. Eric's Personal File")
        print ("3. Sam's Interview")
        print ("4. Owen's Interview")
        print ("5. Katie's Interview")
        print ("6. Margo's Interview")
        print ("7. The Case Evidence")
        print ("8. I don't need to review anything")
        print ("")
        review7 = input("Please enter the number of what you would like to do next:")
        if review7 == 1:
            print ("")
            print ("The Coroner's Report says that although the bottle of pills says that it contained growth hormones,")
            print ("the pills inside the container were actually cyanide. Eric tested positive for the growth hormone")
            print ("and cyanide. He died because he took one of the pills and the cyanide killed him instantly.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 2:
            print ("")
            print ("Eric's Personal File reads that he is one of the star players on the basketball team and does just")
            print ("average in his school work. He likes to go to parties and dance with pretty girls instead of doing")
            print ("his homework and practicing basketball. There are mixed emotions around the campus about Eric's")
            print ("death, some are devastated and others aren't affected at all.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 3:
            print ("")
            print ("Sam says that he didn't really know Eric that well since they weren't in the same social circles.")
            print ("He explains that when he isn't studying, he is reading one of his favorite books, M is for Murder.")
            print ("Sam is in the top of his chemistry class and likes to work in the lab for extra credit, which is")
            print ("where he was at the time of the murder. Sam thinks that Owen is the killer since Owen is always")
            print ("pushing Eric to be a better player and stop messing around.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 4:
            print ("")
            print ("Owen explains that he pushes Eric because he sees that Eric has the potential to be a better player")
            print ("if he puts in the time and effort. Owen has previously been arrested for assault ten years back,")
            print ("but claims he isn't like that anymore. Owen devotes most of his time to basketball, so he was at")
            print ("the supply store getting more balls for the big game. Owen thinks that Katie is the killer because")
            print ("she is always with him and was mad because he was giving all his time to basketball.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 5:
            print ("")
            print ("Katie is really upset and starts crying during the interview saying that she doesn't know what")
            print ("she will do now that Eric is gone. She says that she loved Eric and would never do anything to")
            print ("hurt him. During her free time she likes to go to parties and hang out with Eric, Katie was at a")
            print ("cheerleading practice at time of Eric's murder. Katie says that Margo is the killer because she")
            print ("was jealous of Katie and Eric's relationship, and Margo couldn't stand it.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 6:
            print ("")
            print ("Margo was shocked that anyone wanted to kill Eric, she said he was always a kind, gentleman around")
            print ("her. She was upset because Eric was saying that he wanted to get back together with her but kept")
            print ("going back to Katie. Margo also loves reading and writing, she was at the library at the time")
            print ("of Eric's murder working on her book. Margo says that Katie is the killer because she wanted Eric")
            print ("all for herself and if she couldn't have him no one could.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        elif review7 == 7:
            print ("")
            print ("Case Evidence. Owen's name was on the bottle of pills. Margo had pictures of the bottle and pills")
            print ("on her phone. Katie insisted that she was innocent. Sam had access to Eric's stuff.")
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
        else:
            print ("")
            print ("Now that we have all the evidence lets get our killer!")
    else:
        print ("")
        print ("Now that we have all the evidence lets get our killer!")
    print ("")
    print ("Now that you have looked over all the evidence and interviewed all the suspects, you can decide who the")
    print ("killer is! You will only get two chances to find the killer. Good Luck!")
    print ("")
    print ("1. Sam")
    print ("2. Owen")
    print ("3. Katie")
    print ("4. Margo")
    print ("")
    killer = input("Please enter the number of who you think the killer is:")
    if killer == 1:
        print ("")
        print ("Yay! You caught the killer! Sam is the killer! He thought he would get away with the crime because he")
        print ("believed he was smart enough to elude the police. Sam confessed that he never liked Eric because he")
        print ("always got all the girls and was invited to all the parties, while Sam didn't. If it wasn't for you")
        print ("detective Sam might have gotten away with murder!")
        print ("")
        print ("Great Job Detective! Thanks for playing!")
    elif killer == 2:
        print ("")
        print ("Sorry Owen is not the killer, you get one more try detective.")
        print ("")
        print ("1. Sam")
        print ("2. Owen")
        print ("3. Katie")
        print ("4. Margo")
        print ("")
        killer2 = input("Please enter the number of who you think the killer is:")
        if killer2 == 1:
            print ("")
            print ("Yay! You caught the killer! Sam is the killer! He thought he would get away with the crime because")
            print ("he believed he was smart enough to elude the police. Sam confessed that he never liked Eric because")
            print ("he always got all the girls and was invited to all the parties, while Sam didn't. If it wasn't for")
            print ("you detective Sam might have gotten away with murder!")
            print ("")
            print ("Great Job Detective! Thanks for playing!")
        elif killer2 == 2:
            print ("")
            print ("Sorry Owen is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        elif killer2 == 3:
            print ("")
            print ("Sorry Katie is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        else:
            print ("")
            print ("Sorry Margo is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
    elif killer == 3:
        print ("")
        print ("Sorry Katie is not the killer, you get one more try detective.")
        print ("")
        print ("1. Sam")
        print ("2. Owen")
        print ("3. Katie")
        print ("4. Margo")
        print ("")
        killer3 = input("Please enter the number of who you think the killer is:")
        if killer3 == 1:
            print ("")
            print ("Yay! You caught the killer! Sam is the killer! He thought he would get away with the crime because")
            print ("he believed he was smart enough to elude the police. Sam confessed that he never liked Eric because")
            print ("he always got all the girls and was invited to all the parties, while Sam didn't. If it wasn't for")
            print ("you detective Sam might have gotten away with murder!")
            print ("")
            print ("Great Job Detective! Thanks for playing!")
        elif killer3 == 2:
            print ("")
            print ("Sorry Owen is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        elif killer3 == 3:
            print ("")
            print ("Sorry Katie is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        else:
            print ("")
            print ("Sorry Margo is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
    else:
        print ("")
        print ("Sorry Margo is not the killer, you get one more try detective.")
        print ("")
        print ("1. Sam")
        print ("2. Owen")
        print ("3. Katie")
        print ("4. Margo")
        print ("")
        killer4 = input("Please enter the number of who you think the killer is:")
        if killer4 == 1:
            print ("")
            print ("Yay! You caught the killer! Sam is the killer! He thought he would get away with the crime because")
            print ("he believed he was smart enough to elude the police. Sam confessed that he never liked Eric because")
            print ("he always got all the girls and was invited to all the parties, while Sam didn't. If it wasn't for")
            print ("you detective Sam might have gotten away with murder!")
            print ("")
            print ("Great Job Detective! Thanks for playing!")
        elif killer4 == 2:
            print ("")
            print ("Sorry Owen is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        elif killer4 == 3:
            print ("")
            print ("Sorry Katie is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
        else:
            print ("")
            print ("Sorry Margo is not the killer.")
            print ("")
            print ("Better luck next time detective. Thanks for playing!")
main ()
